services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: FE-dungeon
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - JSDungeons

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: BE-dungeon
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_URI=${MYSQLURI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    networks:
      - JSDungeons

  database:
    image: mysql:latest
    container_name: DB-dungeon
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p${ROOT_PASSWORD}"
      interval: 2s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - JSDungeons

networks:
  JSDungeons:
    driver: bridge
